swagger: '2.0'
info:
  title: Vote Service
  version: 0.0.1
paths:
  /health:
    get:
      tags:
      - "probe"
      summary: "Health endpoint for container orchestration"
      description: "Return 200"
      responses:
        200:
          description: "Healthy"
  /vote/{voteId}:
    get:
      tags:
      - "vote"
      summary: "Find vote by ID"
      description: "Return a single vote"
      operationId: "getVoteById"
      produces:
      - "application/json"
      parameters:
      - name: "voteId"
        in: "path"
        description: "ID of vote to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Vote"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Vote not found"

definitions:
  Vote:
    type: object
    properties:
      id:
        type: integer
        format: int64
      topic:
        type: string
        example: What's your favorite song?
      options:
        type: array
        items:
          type: string
        example: ["Someone Like You", "Lemon", "What a Wonderful World"]
      